### ISSUE TITLE
Avoid suggesting unnecessary module name alias

### ISSUE THREAD

**Issue by tfausak** [EduardSergeev/vscode-haskutil#48]
👋 Hi! Thanks for the great tool. I've been using it recently with the simple GHC extension in VSCode. I ran into a tiny little issue that I think comes from this extension, but please point me elsewhere if that's not the case. 

When suggesting an import the aliased name can be the same as the module name. For example trying to use `Say.sayShow` correctly suggests importing `Say`, but unfortunately also suggests aliasing the import:

![image](https://user-images.githubusercontent.com/408753/158287351-d431dbfc-0e74-497d-abbb-752fae0da259.png)

This isn't wrong, but it is a little surprising and unnecessary. Instead of suggesting `import qualified Say as Say`, it would be nice if haskutil suggested `import qualified Say`.

**Comment by EduardSergeev** [comment]
@tfausak, thank you for your bug report.

Yes, it is the issue of this extension (a case I have not thought about actually).
It is fixed on [branch](https://github.com/EduardSergeev/vscode-haskutil/tree/fix/qualified) but I decided not to merge it straight away because the tests [are broken](https://github.com/EduardSergeev/vscode-haskutil/runs/5565418751?check_suite_focus=true#step:5:234) at the moment so it might take some time for me to fix them. I might merge the fix regardless in the next few days anyway, will see how it goes.

**Comment by tfausak** [comment]
Thanks!
